BRIDGE_PAGE_STYLE = r"""

:root{color-scheme:light dark;--sp-bg:#f4f8f7;--sp-panel:#ffffff;--sp-panel-alt:#fbfefe;--sp-line:#c7e2db;--sp-soft-line:#dce8e5;--sp-ink:#132127;--sp-muted:#5e6c78;--sp-accent:#0f766e;--sp-accent-2:#14b8a6;--sp-soft:#e9f7f3;--sp-warn:#a45a00;--sp-danger:#b42318;--sp-shadow:0 24px 60px rgba(15,118,110,.12)}
*{box-sizing:border-box}body{margin:0;min-height:100vh;background:linear-gradient(180deg,#f9fbfb 0%,var(--sp-bg) 100%);color:var(--sp-ink);font:15px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.bridge-shell{min-height:100vh;display:grid;place-items:center;padding:28px}.bridge-card{width:min(1040px,100%);overflow:hidden;border:1px solid var(--sp-line);border-radius:14px;background:var(--sp-panel);box-shadow:var(--sp-shadow)}
.bridge-header{display:grid;grid-template-columns:auto 1fr auto;gap:18px;align-items:center;padding:28px 30px;border-bottom:1px solid var(--sp-line);background:linear-gradient(90deg,#f3fbf8 0%,#fff 76%)}.bridge-mark{width:54px;height:54px;border-radius:14px;display:grid;place-items:center;background:var(--sp-accent);color:#fff;font-weight:800;letter-spacing:.02em;box-shadow:0 14px 30px rgba(15,118,110,.25)}.bridge-kicker{margin:0 0 4px;color:var(--sp-accent);font-size:12px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.bridge-title{margin:0;font-size:26px;line-height:1.15}.bridge-copy{margin:8px 0 0;color:var(--sp-muted);font-size:15px}.bridge-badge{padding:7px 13px;border:1px solid var(--sp-line);border-radius:999px;background:var(--sp-soft);color:var(--sp-accent);font-weight:700;white-space:nowrap}
.bridge-body{padding:26px 30px 30px}.status-panel{display:grid;gap:10px;margin-bottom:24px}.state-label{font-size:20px;font-weight:800}.status-text{margin:0;color:var(--sp-muted)}.progress{height:10px;overflow:hidden;border-radius:999px;background:#edf2f2}.progress span{position:relative;display:block;width:8%;height:100%;overflow:hidden;border-radius:inherit;background:linear-gradient(90deg,var(--sp-accent),var(--sp-accent-2));transition:width .25s ease}.bridge-card[data-status="failed"] .progress span,.bridge-card[data-status="expired"] .progress span{background:linear-gradient(90deg,#b42318,#ef4444)}.bridge-card[data-status="cancelled"] .progress span,.bridge-card[data-status="disconnected"] .progress span{background:linear-gradient(90deg,#a45a00,#f59e0b)}.bridge-card[data-status="running"] .progress span::after,.bridge-card[data-status="cancel_requested"] .progress span::after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,transparent,rgba(255,255,255,.42),transparent);animation:sp-progress-sweep 1.2s linear infinite}@keyframes sp-progress-sweep{from{transform:translateX(-100%)}to{transform:translateX(100%)}}
.preview-panel{display:grid;grid-template-columns:minmax(0,1fr) minmax(320px,440px);gap:18px;align-items:start;margin:0 0 18px;padding:16px;border:1px solid var(--sp-soft-line);border-radius:12px;background:var(--sp-panel-alt)}.preview-label{margin:0 0 6px;color:var(--sp-muted);font-size:12px;font-weight:800;letter-spacing:.06em;text-transform:uppercase}.target-url{margin:0;overflow-wrap:anywhere;color:var(--sp-ink);font-weight:700}.copy-status{min-height:0;margin:12px 0 0;padding:0;color:var(--sp-muted);font-size:14px;opacity:0;transform:translateY(-2px);transition:opacity .16s ease,transform .16s ease}.copy-status[data-visible="true"]{min-height:34px;padding:7px 10px;border:1px solid var(--sp-line);border-radius:8px;background:var(--sp-soft);color:var(--sp-accent);opacity:1;transform:translateY(0)}.copy-status[data-state="error"]{border-color:#f0b7b2;background:#fff5f5;color:var(--sp-danger)}
.screenshot-frame{width:100%;min-height:220px;aspect-ratio:16/9;display:grid;place-items:center;overflow:hidden;border:1px solid var(--sp-soft-line);border-radius:10px;background:#f3f7f7;cursor:pointer;padding:0;text-align:inherit;transition:border-color .16s ease,box-shadow .16s ease}.screenshot-frame:disabled{cursor:not-allowed}.screenshot-frame.has-image:hover{border-color:var(--sp-accent);box-shadow:0 0 0 3px rgba(15,118,110,.1)}.screenshot-frame img{display:none;width:100%;height:100%;object-fit:contain;background:#fff}.screenshot-frame.has-image img{display:block}.screenshot-frame.has-image .screenshot-empty{display:none}.screenshot-empty{padding:18px;color:var(--sp-muted);text-align:center}.screenshot-meta{min-height:20px;margin:8px 0 0;color:var(--sp-muted);font-size:13px}
.preview-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.preview-button,.modal-close{min-height:38px;padding:0 13px;border:1px solid #b9dcd5;border-radius:8px;background:#fff;color:var(--sp-accent);font:inherit;font-weight:700;cursor:pointer}.preview-button:disabled,.modal-close:disabled{cursor:not-allowed;opacity:.55}.screenshot-frame:focus-visible,.preview-button:focus-visible,.modal-close:focus-visible{outline:3px solid rgba(15,118,110,.35);outline-offset:2px}
	.screenshot-modal{position:fixed;inset:0;z-index:20;display:none;place-items:center;padding:28px;background:rgba(10,18,24,.72);overscroll-behavior:contain}.screenshot-modal[data-open="true"]{display:grid}.modal-card{width:min(1180px,100%);max-height:92vh;display:grid;grid-template-rows:auto auto minmax(0,1fr);overflow:hidden;border:1px solid #25443f;border-radius:14px;background:#081311;box-shadow:0 28px 90px rgba(0,0,0,.42)}.modal-bar{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 14px;border-bottom:1px solid #1e3934;color:#e7f7f3}.modal-title{margin:0;font-size:15px;font-weight:800}.modal-actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center;justify-content:flex-end}.modal-copy-status{display:none;margin:0;padding:0 14px 10px;color:#b7d6cf;font-size:13px;font-weight:600;text-align:right}.modal-copy-status[data-visible="true"]{display:block}.modal-copy-status[data-state="error"]{color:#fca5a5}.modal-close{border-color:#35665f;background:#10211e;color:#e7f7f3}.modal-image{display:block;width:100%;height:100%;max-height:calc(92vh - 82px);object-fit:contain;background:#030807}
	.step-summary{margin:0 0 10px;color:var(--sp-muted);font-size:13px;font-weight:700}.steps{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:0 0 24px;padding:0;list-style:none}.step{min-height:70px;position:relative;padding:12px;border:1px solid var(--sp-soft-line);border-radius:10px;background:#fafdfc;color:var(--sp-muted)}.step-index{display:inline-grid;place-items:center;width:22px;height:22px;margin-bottom:8px;border-radius:999px;background:#edf3f2;color:var(--sp-muted);font-size:12px;font-weight:700}.step.done{border-color:#a9d8cd;background:#f2fbf8;color:var(--sp-accent)}.step.done .step-index,.step.current .step-index{background:var(--sp-accent);color:#fff}.step.current{border-color:var(--sp-accent);color:var(--sp-ink);box-shadow:0 0 0 2px rgba(15,118,110,.08)}.step.failed{border-color:#f0b7b2;background:#fff5f5;color:var(--sp-danger);box-shadow:0 0 0 2px rgba(180,35,24,.08)}.step.failed .step-index{background:var(--sp-danger);color:#fff}
.content-section{margin-top:4px;padding-top:22px;border-top:1px solid #e7eeee}.section-head{display:flex;justify-content:space-between;gap:14px;align-items:end;margin-bottom:14px}.section-head h2{margin:0;font-size:18px}.section-head p{margin:0;color:var(--sp-muted)}.content-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.content-card{min-height:118px;padding:14px;border:1px solid var(--sp-soft-line);border-radius:10px;background:var(--sp-panel-alt)}.content-card h3{margin:0 0 10px;font-size:15px}.content-card ul{display:grid;gap:6px;margin:0;padding-left:18px;color:var(--sp-muted)}
.bridge-footer{display:flex;flex-wrap:wrap;gap:10px;align-items:center;justify-content:space-between;margin-top:24px;padding-top:20px;border-top:1px solid #e7eeee}.bridge-note{margin:0;color:var(--sp-muted)}.pills{display:flex;flex-wrap:wrap;gap:8px}.pill{padding:6px 10px;border:1px solid #d6e7e3;border-radius:999px;color:var(--sp-muted);background:var(--sp-panel-alt);font-size:13px}.bridge-card[data-status="completed"] .bridge-badge{border-color:#a9d8cd;background:#e8f8f1;color:var(--sp-accent)}.bridge-card[data-status="failed"] .bridge-badge,.bridge-card[data-status="expired"] .bridge-badge{border-color:#f0b7b2;background:#fff5f5;color:var(--sp-danger)}.bridge-card[data-status="cancelled"] .bridge-badge,.bridge-card[data-status="disconnected"] .bridge-badge{border-color:#f0d2a8;background:#fff8ed;color:var(--sp-warn)}
		@media (prefers-color-scheme:dark){:root{--sp-bg:#091312;--sp-panel:#101b1a;--sp-panel-alt:#0d1716;--sp-line:#244842;--sp-soft-line:#1f3935;--sp-ink:#ecfdf8;--sp-muted:#9fb8b3;--sp-soft:#12302c;--sp-shadow:0 24px 60px rgba(0,0,0,.35)}body{background:linear-gradient(180deg,#07100f 0%,var(--sp-bg) 100%)}.bridge-header{background:linear-gradient(90deg,#0f2522 0%,#101b1a 76%)}.progress{background:#18302d}.screenshot-frame{background:#0a1312}.screenshot-frame img{background:#07100f}.preview-button{background:#10211e;border-color:#35665f}.copy-status[data-state="error"]{background:#2a1211;border-color:#7f1d1d;color:#fca5a5}.bridge-card[data-status="failed"] .bridge-badge,.bridge-card[data-status="expired"] .bridge-badge{background:#2a1211;color:#fca5a5}.bridge-card[data-status="cancelled"] .bridge-badge,.bridge-card[data-status="disconnected"] .bridge-badge{background:#2a1d0b;color:#fbbf24}.content-section,.bridge-footer{border-color:#1f3935}.step{background:#0d1716}.step.done{background:#102822}.step.failed{border-color:#7f1d1d;background:#2a1211;color:#fca5a5}.step.failed .step-index{background:#ef4444;color:#fff}.pill{border-color:#244842}}
	@media (max-width:760px){.bridge-shell{padding:14px}.bridge-header{grid-template-columns:auto 1fr;padding:20px}.bridge-badge{grid-column:1/-1;justify-self:start}.bridge-body{padding:20px}.preview-panel,.content-grid{grid-template-columns:1fr}.screenshot-frame{min-height:180px}.steps{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.step{min-height:62px;padding:10px}.step-index{width:21px;height:21px;margin-bottom:5px}.step div{font-size:12px;line-height:1.25}.bridge-title{font-size:22px}.screenshot-modal{padding:14px}.modal-bar,.section-head{align-items:flex-start;flex-direction:column}.modal-actions{width:100%;justify-content:flex-end}.modal-copy-status{text-align:left}}
@media (hover:none){.preview-button,.modal-close{min-height:44px;min-width:44px}}
@media (prefers-reduced-motion:reduce){.bridge-card[data-status="running"] .progress span::after,.bridge-card[data-status="cancel_requested"] .progress span::after{animation:none}.copy-status,.progress span,.screenshot-frame{transition:none}}

"""

BRIDGE_PAGE_SCRIPT = r"""

const config=JSON.parse(document.getElementById('stackprism-agent-bridge-config').textContent);
	const ids=['status','stateLabel','statusBadge','progressBar','bridgeCard','targetUrl','screenshotFrame','targetScreenshot','screenshotMeta','screenshotDownload','copyScreenshot','copyAllInfo','copyStatus','modalCopyStatus','stepSummary','profileContentSection','profileContentGrid','screenshotModal','modalScreenshot','modalClose','modalDownload','modalCopyScreenshot'];
const el=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
const steps=[...document.querySelectorAll('[data-phase]')];
let currentScreenshot=null,currentCopyText='',copyStatusTimer=0;
const phases=['bridge_connected','request_loaded','target_opening','target_loaded','detecting_tech','profiling_experience','posting_profile','cleanup'];
const phaseLabels={bridge_connected:'扩展已连接',request_loaded:'读取采集请求',target_opening:'打开目标页面',target_loaded:'目标页面已加载',detecting_tech:'识别技术栈',profiling_experience:'分析视觉与体验',posting_profile:'回传 Profile',cleanup:'清理采集环境'};
const statusLabels={queued:'等待扩展连接',waiting_extension:'等待扩展连接',running:'正在采集',cancel_requested:'正在取消',cancelled:'已取消',completed:'采集完成',failed:'采集失败',expired:'结果已过期',disconnected:'连接已关闭'};
const finalStatuses=['completed','failed','cancelled','expired','disconnected'];
const setStatus=value=>{el.status.textContent=value};
	const setCopyStatus=(node,value,type='ok')=>{node.textContent=value;node.dataset.state=type;node.dataset.visible=value?'true':'false';};
	const showCopyStatus=(value,type='ok')=>{if(copyStatusTimer)clearTimeout(copyStatusTimer);setCopyStatus(el.copyStatus,'');setCopyStatus(el.modalCopyStatus,'');setCopyStatus(modalOpen()?el.modalCopyStatus:el.copyStatus,value,type);if(value)copyStatusTimer=setTimeout(()=>{setCopyStatus(el.copyStatus,'');setCopyStatus(el.modalCopyStatus,'');},2600);};
const screenshotExtension=()=>currentScreenshot?.mimeType==='image/png'?'png':currentScreenshot?.mimeType==='image/webp'?'webp':'jpg';
const screenshotFilename=()=>('stackprism-'+config.captureId+'-screenshot.'+screenshotExtension());
const formatBytes=value=>{const bytes=Number(value);if(!Number.isFinite(bytes)||bytes<=0)return '';if(bytes<1024)return bytes+' B';if(bytes<1048576)return Math.round(bytes/1024)+' KB';return (bytes/1048576).toFixed(1)+' MB';};
const screenshotMetaText=screenshot=>[screenshot.mimeType||'',formatBytes(screenshot.byteLength),screenshot.scope||''].filter(Boolean).join(' · ')||'截图已包含';
	const setScreenshot=screenshot=>{
	currentScreenshot=screenshot?.dataUrl?screenshot:null;
	if(currentScreenshot){if(el.targetScreenshot.src!==currentScreenshot.dataUrl)el.targetScreenshot.src=currentScreenshot.dataUrl;if(el.modalScreenshot.src!==currentScreenshot.dataUrl)el.modalScreenshot.src=currentScreenshot.dataUrl;el.targetScreenshot.alt='目标页面截图预览';el.modalScreenshot.alt='目标页面截图放大预览';}else{el.targetScreenshot.removeAttribute('src');el.modalScreenshot.removeAttribute('src');el.targetScreenshot.alt='';el.modalScreenshot.alt='';}
	el.screenshotFrame.classList.toggle('has-image',Boolean(currentScreenshot));
el.screenshotMeta.textContent=currentScreenshot?screenshotMetaText(currentScreenshot):'截图可用后会显示格式与范围';
for(const item of [el.screenshotFrame,el.screenshotDownload,el.copyScreenshot,el.modalDownload,el.modalCopyScreenshot])item.disabled=!currentScreenshot;
};
	const invalidateScreenshot=()=>{currentScreenshot=null;el.targetScreenshot.removeAttribute('src');el.modalScreenshot.removeAttribute('src');el.targetScreenshot.alt='';el.modalScreenshot.alt='';el.screenshotFrame.classList.remove('has-image');el.screenshotMeta.textContent='截图预览无法加载';for(const item of [el.screenshotFrame,el.screenshotDownload,el.copyScreenshot,el.modalDownload,el.modalCopyScreenshot])item.disabled=true;showCopyStatus('截图预览无法加载，可重新采集或读取 raw profile。','error');};
const downloadScreenshot=()=>{if(!currentScreenshot)return;const link=document.createElement('a');link.href=currentScreenshot.dataUrl;link.download=screenshotFilename();document.body.append(link);link.click();link.remove();};
const copyText=async()=>{if(!currentCopyText)return;try{await navigator.clipboard.writeText(currentCopyText);showCopyStatus('已复制全部信息。');}catch{showCopyStatus('复制失败：浏览器未允许写入剪切板。','error');}};
const screenshotBlob=()=>{const [meta,data]=currentScreenshot.dataUrl.split(',',2);const mime=/^data:([^;]+);base64$/i.exec(meta)?.[1]||currentScreenshot.mimeType||'image/jpeg';const binary=atob(data||'');const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new Blob([bytes],{type:mime});};
const clipboardScreenshotBlob=async()=>{const blob=screenshotBlob();if(blob.type==='image/png')return blob;const bitmap=await createImageBitmap(blob);try{const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const context=canvas.getContext('2d');if(!context)throw new Error('Canvas unavailable');context.drawImage(bitmap,0,0);return await new Promise((resolve,reject)=>canvas.toBlob(output=>output?resolve(output):reject(new Error('PNG conversion failed')),'image/png'));}finally{bitmap.close?.();}};
const copyScreenshot=async()=>{if(!currentScreenshot)return;try{const blob=await clipboardScreenshotBlob();await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);showCopyStatus('已复制截图。');}catch{showCopyStatus('复制截图失败：浏览器未允许写入剪切板，或截图格式无法转换。','error');}};
const modalOpen=()=>el.screenshotModal.dataset.open==='true';
const modalControls=()=>[...el.screenshotModal.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex="-1"])')];
const openScreenshot=()=>{if(currentScreenshot){el.screenshotModal.dataset.open='true';document.body.style.overflow='hidden';el.modalClose.focus();}};
		const closeScreenshot=()=>{if(!modalOpen())return;el.screenshotModal.dataset.open='false';setCopyStatus(el.modalCopyStatus,'');document.body.style.overflow='';const restore=el.screenshotFrame.disabled?el.bridgeCard:el.screenshotFrame;restore.focus({preventScroll:true});};
const renderSummary=summary=>{const cards=Array.isArray(summary?.cards)?summary.cards:[];el.profileContentGrid.replaceChildren();el.profileContentSection.hidden=!cards.length;for(const card of cards){const node=document.createElement('article');node.className='content-card';const title=document.createElement('h3');title.textContent=card.title||'Profile';const list=document.createElement('ul');for(const item of Array.isArray(card.items)?card.items:[]){const li=document.createElement('li');li.textContent=item;list.append(li);}node.append(title,list);el.profileContentGrid.append(node);}};
		const updateSteps=(phase,status)=>{const index=status==='completed'?phases.length-1:Math.max(0,phases.indexOf(phase));const safeIndex=index<0?0:index;const failed=status==='failed';steps.forEach(step=>{const stepIndex=phases.indexOf(step.dataset.phase);const current=stepIndex===safeIndex&&!finalStatuses.includes(status);const failedCurrent=failed&&stepIndex===safeIndex;step.classList.toggle('done',stepIndex<safeIndex||status==='completed');step.classList.toggle('current',current);step.classList.toggle('failed',failedCurrent);if(current||failedCurrent)step.setAttribute('aria-current','step');else step.removeAttribute('aria-current');});el.progressBar.style.width=(status==='completed'?100:Math.max(8,Math.round(((safeIndex+1)/phases.length)*100)))+'%';const phaseLabel=phaseLabels[phase]||phase||status;el.stepSummary.textContent=finalStatuses.includes(status)?('结果：'+(statusLabels[status]||status)+' · '+phaseLabel):('当前步骤：'+(safeIndex+1)+'/'+phases.length+' '+phaseLabel);};
const render=body=>{const status=body?.status||'waiting_extension';const phase=body?.phase||'bridge_connected';const label=statusLabels[status]||status;const preview=body?.preview||{};el.bridgeCard.dataset.status=status;el.bridgeCard.dataset.phase=phase;el.stateLabel.textContent=label;el.statusBadge.textContent=label;setStatus(body?.error?.code||phaseLabels[phase]||status);el.targetUrl.textContent=preview.targetUrl||config.targetUrl||'等待读取目标网址';setScreenshot(preview.screenshot);currentCopyText=typeof preview.copyText==='string'?preview.copyText:'';el.copyAllInfo.disabled=!currentCopyText;renderSummary(preview.contentSummary);updateSteps(phase,status);};
el.screenshotFrame.addEventListener('click',openScreenshot);el.screenshotDownload.addEventListener('click',downloadScreenshot);el.copyScreenshot.addEventListener('click',copyScreenshot);el.copyAllInfo.addEventListener('click',copyText);el.modalDownload.addEventListener('click',downloadScreenshot);el.modalCopyScreenshot.addEventListener('click',copyScreenshot);el.modalClose.addEventListener('click',closeScreenshot);el.targetScreenshot.addEventListener('error',invalidateScreenshot);el.modalScreenshot.addEventListener('error',invalidateScreenshot);
el.screenshotModal.addEventListener('click',event=>{if(event.target===el.screenshotModal)closeScreenshot();});
document.addEventListener('keydown',event=>{if(!modalOpen())return;if(event.key==='Escape'){closeScreenshot();return;}if(event.key!=='Tab')return;const controls=modalControls();if(!controls.length)return;const first=controls[0],last=controls[controls.length-1];if(!el.screenshotModal.contains(document.activeElement)){event.preventDefault();(event.shiftKey?last:first).focus();}else if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}});
const poll=async()=>{try{const res=await fetch('/v1/captures/'+config.captureId,{headers:{Authorization:'Bearer '+config.bridgeToken},cache:'no-store'});const body=await res.json();if(!res.ok){render({status:'failed',phase:'cleanup',error:{code:body?.error?.code||'Bridge request failed.'}});return;}render(body);if(finalStatuses.includes(body.status))return;}catch{render({status:'disconnected',phase:'cleanup',error:{code:'本机 bridge 服务已关闭，当前页面无法继续读取状态。'}});return;}setTimeout(poll,1000);};
poll();

"""
